server:
  port: 1234

spring:
  application:
    name: libraryapi
#  profiles:
#    active: production
# SPRING_PROFILES_ACTIVE
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

logging:
  file:
    name: app.log
  pattern:
    console: "%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n"
  level:
    root: warn
    io:
      github:
        enzopavani: trace
    org:
      springframework:
        web: debug
        security: trace
    # trace, debug, info, warn, error

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  override-with-generic-response: false


# production
---
spring:
  config:
    activate:
      on-profile: production
  jpa:
    show-sql: false


# homologação
---
spring:
  config:
    activate:
      on-profile: homologacao